# kubectl auth can-i --list -n psp-demo --as=system:serviceaccount:psp-demo:psp-demo-sa
# kubectl apply -f psp_demo_pod.yaml --as=system:serviceaccount:psp-demo:psp-demo-sa
# kubectl delete -f psp_demo_pod.yaml --as=system:serviceaccount:psp-demo:psp-demo-sa
# https://blog.container-solutions.com/linux-capabilities-in-practice
# https://kubernetes.io/docs/concepts/policy/pod-security-policy/#authorizing-policies
# alias kubectl-user='kubectl --as=system:serviceaccount:psp-demo:psp-demo-sa -n psp-demo'

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: psp-demo
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      #serviceAccountName: psp-demo-sa
      containers:
      - name: webapp
        image: nginx
        securityContext:
          privileged: false

# minikube start --extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy --addons=pod-security-policy
# 00000000a80425fb          